# Generated by Django 4.0.3 on 2022-03-07 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(help_text='this is name of planer', max_length=150, verbose_name='Название')),
                ('data', models.DateTimeField(auto_now_add=True, null=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/image')),
            ],
        ),
    ]
